version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "10:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: pkg
    versions:
    - 4.4.9
    - 4.5.0
    - 4.5.1
    - 5.0.0
  - dependency-name: y18n
    versions:
    - 4.0.1
  - dependency-name: lodash
    versions:
    - 4.17.20
  - dependency-name: elliptic
    versions:
    - 6.5.3
